/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex1;

public class App {
    public static void main(String[] args) {
        // Create two screens
        Screen screen = new Screen();
        Phone phone = new Phone();
        // Create a datastore
        DataStore dataStore = new DataStore(new ObserverTracker());
        // Connect the dataStore and the screens
        dataStore.getTracker().add(screen);
        dataStore.getTracker().add(phone);

        // Update data in the dataStore
        String data = "Some data";
        dataStore.setData(data);
        dataStore.sendUpdate();

        data = "New data";
        dataStore.setData(data);
        dataStore.sendUpdate();
    }
}
